// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinWindow uITxtDNWindow = this.UIĐăngnhậpWindow.UIĐăngnhậpClient.UITxtDNWindow;
            WinEdit uITxtDNEdit = this.UIĐăngnhậpWindow.UITxtDNWindow.UITxtDNEdit;
            WinEdit uITxtMKEdit = this.UIĐăngnhậpWindow.UITxtMKWindow.UITxtMKEdit;
            WinButton uIĐăngnhậpButton = this.UIĐăngnhậpWindow.UIĐăngnhậpWindow1.UIĐăngnhậpButton;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            #endregion

            // Click 'txtDN' window
            Mouse.Click(uITxtDNWindow, new Point(72, 0));

            // Type '0993248092348' in 'txtDN' text box
            uITxtDNEdit.Text = this.RecordedMethod1Params.UITxtDNEditText;

            // Click 'txtMK' text box
            Mouse.Click(uITxtMKEdit, new Point(100, 6));

            // Type '********' in 'txtMK' text box
            Keyboard.SendKeys(uITxtMKEdit, this.RecordedMethod1Params.UITxtMKEditSendKeys, true);

            // Click 'Đăng nhập' button
            Mouse.Click(uIĐăngnhậpButton, new Point(44, 19));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(27, 10));
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UIĐăngnhậpWindow UIĐăngnhậpWindow
        {
            get
            {
                if ((this.mUIĐăngnhậpWindow == null))
                {
                    this.mUIĐăngnhậpWindow = new UIĐăngnhậpWindow();
                }
                return this.mUIĐăngnhậpWindow;
            }
        }
        
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow();
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UIĐăngnhậpWindow mUIĐăngnhậpWindow;
        
        private UIOKWindow mUIOKWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type '0993248092348' in 'txtDN' text box
        /// </summary>
        public string UITxtDNEditText = "0993248092348";
        
        /// <summary>
        /// Type '********' in 'txtMK' text box
        /// </summary>
        public string UITxtMKEditSendKeys = "mOL/lXDUSd/hy7K5BZnJEA==";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIĐăngnhậpWindow : WinWindow
    {
        
        public UIĐăngnhậpWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Đăng nhập";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Đăng nhập");
            #endregion
        }
        
        #region Properties
        public UIĐăngnhậpClient UIĐăngnhậpClient
        {
            get
            {
                if ((this.mUIĐăngnhậpClient == null))
                {
                    this.mUIĐăngnhậpClient = new UIĐăngnhậpClient(this);
                }
                return this.mUIĐăngnhậpClient;
            }
        }
        
        public UITxtDNWindow UITxtDNWindow
        {
            get
            {
                if ((this.mUITxtDNWindow == null))
                {
                    this.mUITxtDNWindow = new UITxtDNWindow(this);
                }
                return this.mUITxtDNWindow;
            }
        }
        
        public UITxtMKWindow UITxtMKWindow
        {
            get
            {
                if ((this.mUITxtMKWindow == null))
                {
                    this.mUITxtMKWindow = new UITxtMKWindow(this);
                }
                return this.mUITxtMKWindow;
            }
        }
        
        public UIĐăngnhậpWindow1 UIĐăngnhậpWindow1
        {
            get
            {
                if ((this.mUIĐăngnhậpWindow1 == null))
                {
                    this.mUIĐăngnhậpWindow1 = new UIĐăngnhậpWindow1(this);
                }
                return this.mUIĐăngnhậpWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIĐăngnhậpClient mUIĐăngnhậpClient;
        
        private UITxtDNWindow mUITxtDNWindow;
        
        private UITxtMKWindow mUITxtMKWindow;
        
        private UIĐăngnhậpWindow1 mUIĐăngnhậpWindow1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIĐăngnhậpClient : WinClient
    {
        
        public UIĐăngnhậpClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Đăng nhập";
            this.WindowTitles.Add("Đăng nhập");
            #endregion
        }
        
        #region Properties
        public WinWindow UITxtDNWindow
        {
            get
            {
                if ((this.mUITxtDNWindow == null))
                {
                    this.mUITxtDNWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUITxtDNWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITxtDNWindow.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
                    this.mUITxtDNWindow.WindowTitles.Add("Đăng nhập");
                    #endregion
                }
                return this.mUITxtDNWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUITxtDNWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UITxtDNWindow : WinWindow
    {
        
        public UITxtDNWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtDN";
            this.WindowTitles.Add("Đăng nhập");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtDNEdit
        {
            get
            {
                if ((this.mUITxtDNEdit == null))
                {
                    this.mUITxtDNEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtDNEdit.WindowTitles.Add("Đăng nhập");
                    #endregion
                }
                return this.mUITxtDNEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtDNEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UITxtMKWindow : WinWindow
    {
        
        public UITxtMKWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtMK";
            this.WindowTitles.Add("Đăng nhập");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtMKEdit
        {
            get
            {
                if ((this.mUITxtMKEdit == null))
                {
                    this.mUITxtMKEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtMKEdit.SearchProperties[WinEdit.PropertyNames.Name] = "ĐĂNG NHẬP";
                    this.mUITxtMKEdit.WindowTitles.Add("Đăng nhập");
                    #endregion
                }
                return this.mUITxtMKEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtMKEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIĐăngnhậpWindow1 : WinWindow
    {
        
        public UIĐăngnhậpWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnDN";
            this.WindowTitles.Add("Đăng nhập");
            #endregion
        }
        
        #region Properties
        public WinButton UIĐăngnhậpButton
        {
            get
            {
                if ((this.mUIĐăngnhậpButton == null))
                {
                    this.mUIĐăngnhậpButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIĐăngnhậpButton.SearchProperties[WinButton.PropertyNames.Name] = "Đăng nhập";
                    this.mUIĐăngnhậpButton.WindowTitles.Add("Đăng nhập");
                    #endregion
                }
                return this.mUIĐăngnhậpButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIĐăngnhậpButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "OK";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Button";
            this.WindowTitles.Add("OK");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("OK");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
}
